### ISSUE TITLE
Use on own dataset

### ISSUE THREAD

**Issue by AndreaPisoni** [Orpine/py-R-FCN#8]
Hi, 

How would I go about using this model on my own dataset with different classes? Any pointers?

Thanks!

**Comment by Orpine** [comment]
Hi @AndreaPisoni ,
Besides prepare your own data, you need to modify two layers' num_output: "rfcn_cls", "psroipooled_cls_rois", change the num_output of "rfcn_cls" to [your class_num] * 7 * 7, and the num_output of "psroipooled_cls_rois" to [your class_num]. And you needn't modify num_classes of "input-data" layer since it is useless when using RPN.
